namespace Adr.Semantics.Mappers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text;
    using Adr.Semantics.Models;

    /// <summary>
    /// Renders a collection of <see cref="GlossaryModel"/> entries as a Markdown document.
    /// </summary>
    public static class GlossaryMarkdownMapper
    {
        private const string GeneratedNotice =
            "<!--\n"
            + "This glossary was generated from the ADR semantics server API.\n"
            + "Do not edit this file directly. Retrieve the current markdown from the web API endpoint.\n"
            + "-->\n"
            + "\n"
            + "|Term|Definition|\n"
            + "|:----|:----|\n";

        /// <summary>
        /// Renders the given glossary entries as a Markdown document.
        /// </summary>
        /// <param name="entries">The glossary entries to render.</param>
        /// <param name="glossary">The glossary release metadata.</param>
        /// <returns>A Markdown string ready to be written to a file.</returns>
        public static string Map(
            IEnumerable<GlossaryModel> entries,
            GlossaryVersionModel glossary
        )
        {
            var ordered = (entries ?? Enumerable.Empty<GlossaryModel>())
                .Where(e => !string.IsNullOrWhiteSpace(e?.Term))
                .Where(e => e.PublishToDevHub && e.VerifiedDefinitionFlag)
                .OrderBy(e => e.Term, StringComparer.OrdinalIgnoreCase)
                .ToList();

            var stringBuilder = new StringBuilder();
            stringBuilder
                .Append("---\n")
                .Append("title: Connected Services Glossary of Terms table\n")
                .Append("glossary_id: ")
                .Append(glossary.Id)
                .Append('\n')
                .Append("glossary_version: ")
                .Append(glossary.Version)
                .Append('\n')
                .Append("glossary_published_at: ")
                .Append(glossary.PublishedAt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture))
                .Append("\n---\n\n")
                .Append(GeneratedNotice);

            foreach (var entry in ordered)
            {
                stringBuilder
                    .Append('|')
                    .Append(EscapeCell(entry.Term))
                    .Append('|')
                    .Append(EscapeCell(entry.Definition))
                    .Append("|\n");
            }

            return stringBuilder.ToString();
        }

        private static string EscapeCell(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return string.Empty;
            }

            return value
                .Replace("\r\n", " ")
                .Replace("\n", " ")
                .Replace("\r", " ")
                .Replace("|", "\\|");
        }
    }
}
