namespace Adr.Semantics.Mappers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text;
    using Adr.Semantics.Models;

    /// <summary>
    /// Renders a collection of <see cref="GlossaryModel"/> entries as a Markdown list.
    /// </summary>
    public static class GlossaryMarkdownListMapper
    {
        private const string GeneratedNoticeAndIntroduction =
            "<!--\n"
            + "This glossary was generated from the ADR semantics server API.\n"
            + "Do not edit this file directly. Retrieve the current markdown from the web API endpoint.\n"
            + "-->\n"
            + "\n"
            + "The glossary provides a shared language for Connected Services. As the central source of business and technical terminology, it defines the meaning, context, and intended use of key concepts in clear, plain language. By establishing common definitions, it helps ensure information is interpreted consistently across ministries, systems, and services. It serves as a foundation for the broader semantic layer, complementing data dictionaries, taxonomies, ontologies, knowledge graphs, policy documents, and API specifications to connect information through shared meaning.\n"
            + "\n";

        /// <summary>
        /// Renders the given glossary entries as a Markdown document.
        /// </summary>
        /// <param name="entries">The glossary entries to render.</param>
        /// <param name="glossary">The glossary release metadata.</param>
        /// <returns>A Markdown string ready to be written to a file.</returns>
        public static string Map(
            IEnumerable<GlossaryModel> entries,
            GlossaryVersionModel glossary
        )
        {
            var ordered = (entries ?? Enumerable.Empty<GlossaryModel>())
                .Where(e => !string.IsNullOrWhiteSpace(e?.Term))
                .Where(e => e.PublishToDevHub && e.VerifiedDefinitionFlag)
                .OrderBy(e => e.Term, StringComparer.OrdinalIgnoreCase)
                .ToList();

            var groupedByLetter = ordered
                .GroupBy(entry => GetSectionLetter(entry.Term))
                .OrderBy(group => group.Key == "#" ? "ZZZ" : group.Key, StringComparer.Ordinal)
                .ToList();

            var stringBuilder = new StringBuilder();
            stringBuilder
                .Append("---\n")
                .Append("title: Glossary of Terms\n")
                .Append("glossary_id: ")
                .Append(glossary.Id)
                .Append('\n')
                .Append("glossary_version: ")
                .Append(glossary.Version)
                .Append('\n')
                .Append("glossary_published_at: ")
                .Append(glossary.PublishedAt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture))
                .Append("\n---\n\n")
                .Append(GeneratedNoticeAndIntroduction);

            if (groupedByLetter.Any())
            {
                var links = groupedByLetter
                    .Select(group => $"[{group.Key}](#{GetSectionId(group.Key)})");
                stringBuilder.Append(string.Join(" | ", links)).Append("\n\n");
            }

            foreach (var letterGroup in groupedByLetter)
            {
                stringBuilder
                    .Append("## ")
                    .Append(letterGroup.Key)
                    .Append(" {#")
                    .Append(GetSectionId(letterGroup.Key))
                    .Append("}\n\n");

                foreach (var entry in letterGroup)
                {
                    var keywords = string.Join(
                        ", ",
                        (entry.Keywords ?? Enumerable.Empty<string>())
                            .Where(c => !string.IsNullOrWhiteSpace(c))
                            .Select(c => c.Trim())
                    );

                    var definitionText = entry.Definition?.TrimEnd() ?? string.Empty;
                    var scopeText = entry.Scope?.Trim();
                    var scopeUrl = entry.ScopeUrl?.Trim();

                    stringBuilder
                        .Append("### ")
                        .Append(entry.Term.Trim())
                        .Append(" {#")
                        .Append(GetTermId(entry.StaticId, entry.Name))
                        .Append("}\n\n")
                        .Append(definitionText);

                    if (!string.IsNullOrWhiteSpace(scopeText))
                    {
                        // `Scope` is displayed wrapped in square brackets
                        // whether or not `ScopeUrl` is available for a link.
                        stringBuilder.Append(" [");

                        if (IsValidUrl(scopeUrl))
                        {
                            stringBuilder
                                .Append("[")
                                .Append(scopeText)
                                .Append("](")
                                .Append(scopeUrl)
                                .Append(")");
                        }
                        else
                        {
                            stringBuilder.Append(scopeText);
                        }

                        stringBuilder.Append("]");
                    }

                    stringBuilder
                        .Append("\n\n");
                }
            }

            return stringBuilder.ToString();
        }

        private static string GetSectionLetter(string term)
        {
            var firstCharacter = term?.Trim().FirstOrDefault() ?? null;
            if (firstCharacter.HasValue && char.IsLetter(firstCharacter.Value))
            {
                return char.ToUpperInvariant(firstCharacter.Value).ToString();
            }

            return "#";
        }

        private static string GetSectionId(string sectionLetter)
        {
            return sectionLetter == "#"
                ? "terms-other"
                : $"terms-{sectionLetter.ToLowerInvariant()}";
        }

        private static string GetTermId(string staticId, string name)
        {
            var normalizedId = staticId?.Trim();
            if (!string.IsNullOrWhiteSpace(normalizedId))
            {
                return $"term-{normalizedId.ToLowerInvariant()}";
            }

            // Fallback only for unexpected records missing StaticId.
            return $"term-{name.ToLowerInvariant()}";
        }

        private static bool IsValidUrl(string? text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return false;
            }

            if (!Uri.TryCreate(text, UriKind.Absolute, out var uri))
            {
                return false;
            }

            // Only accept http and https schemes
            if (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps)
            {
                return false;
            }

            // Host must contain at least one dot (`example.com` is valid, `example` and `Data` are not)
            if (!uri.Host.Contains('.'))
            {
                return false;
            }

            return true;
        }
    }
}
