// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createGlossaryDraft, deleteGlossaryDraftTerm, getAllDictionaries, getAllGlossary, getGlossaryDraft, getGlossaryDrafts, getGlossaryEntryById, getGlossaryEntryByTerm, getGlossaryMarkdown, getGlossaryMarkdownList, getGlossarySchema, getGlossaryTermHistory, getGlossaryTermVersion, getGlossaryTermVersions, getGlossaryTermVersionSchema, getGlossaryVersion, getGlossaryVersionEntryByTerm, getGlossaryVersionMarkdown, getGlossaryVersionMarkdownList, getGlossaryVersions, getGlossaryVersionSchema, type Options, publishGlossaryVersion, putGlossaryDraftTerm, rebaseGlossaryDraft } from '../sdk.gen';
import type { CreateGlossaryDraftData, CreateGlossaryDraftResponse, DeleteGlossaryDraftTermData, DeleteGlossaryDraftTermError, DeleteGlossaryDraftTermResponse, GetAllDictionariesData, GetAllDictionariesResponse, GetAllGlossaryData, GetAllGlossaryResponse, GetGlossaryDraftData, GetGlossaryDraftError, GetGlossaryDraftResponse, GetGlossaryDraftsData, GetGlossaryDraftsResponse, GetGlossaryEntryByIdData, GetGlossaryEntryByIdError, GetGlossaryEntryByIdResponse, GetGlossaryEntryByTermData, GetGlossaryEntryByTermError, GetGlossaryEntryByTermResponse, GetGlossaryMarkdownData, GetGlossaryMarkdownListData, GetGlossaryMarkdownListResponse, GetGlossaryMarkdownResponse, GetGlossarySchemaData, GetGlossarySchemaResponse, GetGlossaryTermHistoryData, GetGlossaryTermHistoryError, GetGlossaryTermHistoryResponse, GetGlossaryTermVersionData, GetGlossaryTermVersionError, GetGlossaryTermVersionResponse, GetGlossaryTermVersionSchemaData, GetGlossaryTermVersionSchemaError, GetGlossaryTermVersionSchemaResponse, GetGlossaryTermVersionsData, GetGlossaryTermVersionsError, GetGlossaryTermVersionsResponse, GetGlossaryVersionData, GetGlossaryVersionEntryByTermData, GetGlossaryVersionEntryByTermError, GetGlossaryVersionEntryByTermResponse, GetGlossaryVersionError, GetGlossaryVersionMarkdownData, GetGlossaryVersionMarkdownError, GetGlossaryVersionMarkdownListData, GetGlossaryVersionMarkdownListError, GetGlossaryVersionMarkdownListResponse, GetGlossaryVersionMarkdownResponse, GetGlossaryVersionResponse, GetGlossaryVersionSchemaData, GetGlossaryVersionSchemaError, GetGlossaryVersionSchemaResponse, GetGlossaryVersionsData, GetGlossaryVersionsResponse, PublishGlossaryVersionData, PublishGlossaryVersionError, PublishGlossaryVersionResponse, PutGlossaryDraftTermData, PutGlossaryDraftTermError, PutGlossaryDraftTermResponse, RebaseGlossaryDraftData, RebaseGlossaryDraftError, RebaseGlossaryDraftResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAllDictionariesQueryKey = (options?: Options<GetAllDictionariesData>) => createQueryKey('getAllDictionaries', options);

/**
 * Returns all dictionary information.
 *
 * Returns all dictionary information. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getAllDictionariesOptions = (options?: Options<GetAllDictionariesData>) => queryOptions<GetAllDictionariesResponse, DefaultError, GetAllDictionariesResponse, ReturnType<typeof getAllDictionariesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllDictionaries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllDictionariesQueryKey(options)
});

export const getAllGlossaryQueryKey = (options?: Options<GetAllGlossaryData>) => createQueryKey('getAllGlossary', options);

/**
 * Returns all glossary information.
 *
 * Returns all glossary information. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getAllGlossaryOptions = (options?: Options<GetAllGlossaryData>) => queryOptions<GetAllGlossaryResponse, DefaultError, GetAllGlossaryResponse, ReturnType<typeof getAllGlossaryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllGlossary({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllGlossaryQueryKey(options)
});

export const getGlossaryVersionsQueryKey = (options?: Options<GetGlossaryVersionsData>) => createQueryKey('getGlossaryVersions', options);

/**
 * Returns metadata for all available glossary releases.
 *
 * Returns metadata for all available glossary releases. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryVersionsOptions = (options?: Options<GetGlossaryVersionsData>) => queryOptions<GetGlossaryVersionsResponse, DefaultError, GetGlossaryVersionsResponse, ReturnType<typeof getGlossaryVersionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryVersions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryVersionsQueryKey(options)
});

/**
 * Publishes a glossary draft as a new glossary version.
 *
 * Publishes a glossary draft as a new glossary version. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const publishGlossaryVersionMutation = (options?: Partial<Options<PublishGlossaryVersionData>>): UseMutationOptions<PublishGlossaryVersionResponse, PublishGlossaryVersionError, Options<PublishGlossaryVersionData>> => {
    const mutationOptions: UseMutationOptions<PublishGlossaryVersionResponse, PublishGlossaryVersionError, Options<PublishGlossaryVersionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await publishGlossaryVersion({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getGlossaryVersionQueryKey = (options: Options<GetGlossaryVersionData>) => createQueryKey('getGlossaryVersion', options);

/**
 * Returns all published terms from a specific glossary release.
 *
 * Returns all published terms from a specific glossary release. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryVersionOptions = (options: Options<GetGlossaryVersionData>) => queryOptions<GetGlossaryVersionResponse, GetGlossaryVersionError, GetGlossaryVersionResponse, ReturnType<typeof getGlossaryVersionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryVersion({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryVersionQueryKey(options)
});

export const getGlossarySchemaQueryKey = (options?: Options<GetGlossarySchemaData>) => createQueryKey('getGlossarySchema', options);

/**
 * Returns the current glossary release as reusable OpenAPI schema components.
 *
 * Returns the current glossary release as reusable OpenAPI schema components. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossarySchemaOptions = (options?: Options<GetGlossarySchemaData>) => queryOptions<GetGlossarySchemaResponse, DefaultError, GetGlossarySchemaResponse, ReturnType<typeof getGlossarySchemaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossarySchema({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossarySchemaQueryKey(options)
});

export const getGlossaryVersionSchemaQueryKey = (options: Options<GetGlossaryVersionSchemaData>) => createQueryKey('getGlossaryVersionSchema', options);

/**
 * Returns a specific glossary release as reusable OpenAPI schema components.
 *
 * Returns a specific glossary release as reusable OpenAPI schema components. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryVersionSchemaOptions = (options: Options<GetGlossaryVersionSchemaData>) => queryOptions<GetGlossaryVersionSchemaResponse, GetGlossaryVersionSchemaError, GetGlossaryVersionSchemaResponse, ReturnType<typeof getGlossaryVersionSchemaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryVersionSchema({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryVersionSchemaQueryKey(options)
});

export const getGlossaryMarkdownQueryKey = (options?: Options<GetGlossaryMarkdownData>) => createQueryKey('getGlossaryMarkdown', options);

/**
 * Returns all glossary information rendered as a Markdown table.
 *
 * Returns all glossary information rendered as a Markdown table. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryMarkdownOptions = (options?: Options<GetGlossaryMarkdownData>) => queryOptions<GetGlossaryMarkdownResponse, DefaultError, GetGlossaryMarkdownResponse, ReturnType<typeof getGlossaryMarkdownQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryMarkdown({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryMarkdownQueryKey(options)
});

export const getGlossaryVersionMarkdownQueryKey = (options: Options<GetGlossaryVersionMarkdownData>) => createQueryKey('getGlossaryVersionMarkdown', options);

/**
 * Returns a specific glossary release rendered as a Markdown table.
 *
 * Returns a specific glossary release rendered as a Markdown table. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryVersionMarkdownOptions = (options: Options<GetGlossaryVersionMarkdownData>) => queryOptions<GetGlossaryVersionMarkdownResponse, GetGlossaryVersionMarkdownError, GetGlossaryVersionMarkdownResponse, ReturnType<typeof getGlossaryVersionMarkdownQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryVersionMarkdown({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryVersionMarkdownQueryKey(options)
});

export const getGlossaryMarkdownListQueryKey = (options?: Options<GetGlossaryMarkdownListData>) => createQueryKey('getGlossaryMarkdownList', options);

/**
 * Returns all glossary information rendered as a Markdown list.
 *
 * Returns all glossary information rendered as a Markdown list. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryMarkdownListOptions = (options?: Options<GetGlossaryMarkdownListData>) => queryOptions<GetGlossaryMarkdownListResponse, DefaultError, GetGlossaryMarkdownListResponse, ReturnType<typeof getGlossaryMarkdownListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryMarkdownList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryMarkdownListQueryKey(options)
});

export const getGlossaryVersionMarkdownListQueryKey = (options: Options<GetGlossaryVersionMarkdownListData>) => createQueryKey('getGlossaryVersionMarkdownList', options);

/**
 * Returns a specific glossary release rendered as a Markdown list.
 *
 * Returns a specific glossary release rendered as a Markdown list. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryVersionMarkdownListOptions = (options: Options<GetGlossaryVersionMarkdownListData>) => queryOptions<GetGlossaryVersionMarkdownListResponse, GetGlossaryVersionMarkdownListError, GetGlossaryVersionMarkdownListResponse, ReturnType<typeof getGlossaryVersionMarkdownListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryVersionMarkdownList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryVersionMarkdownListQueryKey(options)
});

export const getGlossaryTermVersionsQueryKey = (options: Options<GetGlossaryTermVersionsData>) => createQueryKey('getGlossaryTermVersions', options);

/**
 * Returns every persisted version of a glossary term.
 *
 * Returns every persisted version of a glossary term. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryTermVersionsOptions = (options: Options<GetGlossaryTermVersionsData>) => queryOptions<GetGlossaryTermVersionsResponse, GetGlossaryTermVersionsError, GetGlossaryTermVersionsResponse, ReturnType<typeof getGlossaryTermVersionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryTermVersions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryTermVersionsQueryKey(options)
});

export const getGlossaryTermHistoryQueryKey = (options: Options<GetGlossaryTermHistoryData>) => createQueryKey('getGlossaryTermHistory', options);

/**
 * Returns the published revisions and invalid submissions for a term selected from a
 * specific glossary release.
 *
 * Returns the published revisions and invalid submissions for a term selected from a
 * specific glossary release. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryTermHistoryOptions = (options: Options<GetGlossaryTermHistoryData>) => queryOptions<GetGlossaryTermHistoryResponse, GetGlossaryTermHistoryError, GetGlossaryTermHistoryResponse, ReturnType<typeof getGlossaryTermHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryTermHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryTermHistoryQueryKey(options)
});

export const getGlossaryTermVersionQueryKey = (options: Options<GetGlossaryTermVersionData>) => createQueryKey('getGlossaryTermVersion', options);

/**
 * Returns a persisted version of a glossary term.
 *
 * Returns a persisted version of a glossary term. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryTermVersionOptions = (options: Options<GetGlossaryTermVersionData>) => queryOptions<GetGlossaryTermVersionResponse, GetGlossaryTermVersionError, GetGlossaryTermVersionResponse, ReturnType<typeof getGlossaryTermVersionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryTermVersion({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryTermVersionQueryKey(options)
});

export const getGlossaryTermVersionSchemaQueryKey = (options: Options<GetGlossaryTermVersionSchemaData>) => createQueryKey('getGlossaryTermVersionSchema', options);

/**
 * Returns a persisted term revision as a reusable OpenAPI Schema Object.
 *
 * Returns a persisted term revision as a reusable OpenAPI Schema Object. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryTermVersionSchemaOptions = (options: Options<GetGlossaryTermVersionSchemaData>) => queryOptions<GetGlossaryTermVersionSchemaResponse, GetGlossaryTermVersionSchemaError, GetGlossaryTermVersionSchemaResponse, ReturnType<typeof getGlossaryTermVersionSchemaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryTermVersionSchema({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryTermVersionSchemaQueryKey(options)
});

export const getGlossaryEntryByIdQueryKey = (options: Options<GetGlossaryEntryByIdData>) => createQueryKey('getGlossaryEntryById', options);

/**
 * Returns the current valid glossary entry identified by its stable UUID.
 *
 * Returns the current valid glossary entry identified by its stable UUID. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryEntryByIdOptions = (options: Options<GetGlossaryEntryByIdData>) => queryOptions<GetGlossaryEntryByIdResponse, GetGlossaryEntryByIdError, GetGlossaryEntryByIdResponse, ReturnType<typeof getGlossaryEntryByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryEntryById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryEntryByIdQueryKey(options)
});

export const getGlossaryEntryByTermQueryKey = (options: Options<GetGlossaryEntryByTermData>) => createQueryKey('getGlossaryEntryByTerm', options);

/**
 * Returns a glossary entry by its human-readable slug.
 *
 * Returns a glossary entry by its human-readable slug. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryEntryByTermOptions = (options: Options<GetGlossaryEntryByTermData>) => queryOptions<GetGlossaryEntryByTermResponse, GetGlossaryEntryByTermError, GetGlossaryEntryByTermResponse, ReturnType<typeof getGlossaryEntryByTermQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryEntryByTerm({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryEntryByTermQueryKey(options)
});

export const getGlossaryVersionEntryByTermQueryKey = (options: Options<GetGlossaryVersionEntryByTermData>) => createQueryKey('getGlossaryVersionEntryByTerm', options);

/**
 * Returns a glossary entry from a specific release by its human-readable slug.
 *
 * Returns a glossary entry from a specific release by its human-readable slug. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryVersionEntryByTermOptions = (options: Options<GetGlossaryVersionEntryByTermData>) => queryOptions<GetGlossaryVersionEntryByTermResponse, GetGlossaryVersionEntryByTermError, GetGlossaryVersionEntryByTermResponse, ReturnType<typeof getGlossaryVersionEntryByTermQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryVersionEntryByTerm({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryVersionEntryByTermQueryKey(options)
});

export const getGlossaryDraftsQueryKey = (options?: Options<GetGlossaryDraftsData>) => createQueryKey('getGlossaryDrafts', options);

/**
 * Returns glossary draft metadata, optionally filtered by lifecycle status.
 *
 * Returns glossary draft metadata, optionally filtered by lifecycle status. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryDraftsOptions = (options?: Options<GetGlossaryDraftsData>) => queryOptions<GetGlossaryDraftsResponse, DefaultError, GetGlossaryDraftsResponse, ReturnType<typeof getGlossaryDraftsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryDrafts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryDraftsQueryKey(options)
});

/**
 * Creates a new draft based on the current glossary release.
 *
 * Creates a new draft based on the current glossary release. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const createGlossaryDraftMutation = (options?: Partial<Options<CreateGlossaryDraftData>>): UseMutationOptions<CreateGlossaryDraftResponse, DefaultError, Options<CreateGlossaryDraftData>> => {
    const mutationOptions: UseMutationOptions<CreateGlossaryDraftResponse, DefaultError, Options<CreateGlossaryDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createGlossaryDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getGlossaryDraftQueryKey = (options: Options<GetGlossaryDraftData>) => createQueryKey('getGlossaryDraft', options);

/**
 * Returns a draft, its calculated draft version, and its effective terms.
 *
 * Returns a draft, its calculated draft version, and its effective terms. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const getGlossaryDraftOptions = (options: Options<GetGlossaryDraftData>) => queryOptions<GetGlossaryDraftResponse, GetGlossaryDraftError, GetGlossaryDraftResponse, ReturnType<typeof getGlossaryDraftQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryDraft({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryDraftQueryKey(options)
});

/**
 * Applies a stale draft's changes to the current glossary release.
 *
 * Applies a stale draft's changes to the current glossary release. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const rebaseGlossaryDraftMutation = (options?: Partial<Options<RebaseGlossaryDraftData>>): UseMutationOptions<RebaseGlossaryDraftResponse, RebaseGlossaryDraftError, Options<RebaseGlossaryDraftData>> => {
    const mutationOptions: UseMutationOptions<RebaseGlossaryDraftResponse, RebaseGlossaryDraftError, Options<RebaseGlossaryDraftData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await rebaseGlossaryDraft({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Removes a term from a draft and records the deletion for audit.
 *
 * Removes a term from a draft and records the deletion for audit. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const deleteGlossaryDraftTermMutation = (options?: Partial<Options<DeleteGlossaryDraftTermData>>): UseMutationOptions<DeleteGlossaryDraftTermResponse, DeleteGlossaryDraftTermError, Options<DeleteGlossaryDraftTermData>> => {
    const mutationOptions: UseMutationOptions<DeleteGlossaryDraftTermResponse, DeleteGlossaryDraftTermError, Options<DeleteGlossaryDraftTermData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteGlossaryDraftTerm({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Adds or replaces a term in a draft and records the submission for audit.
 *
 * Adds or replaces a term in a draft and records the submission for audit. The response contains the requested semantic data or explains why the request could not be completed.
 */
export const putGlossaryDraftTermMutation = (options?: Partial<Options<PutGlossaryDraftTermData>>): UseMutationOptions<PutGlossaryDraftTermResponse, PutGlossaryDraftTermError, Options<PutGlossaryDraftTermData>> => {
    const mutationOptions: UseMutationOptions<PutGlossaryDraftTermResponse, PutGlossaryDraftTermError, Options<PutGlossaryDraftTermData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putGlossaryDraftTerm({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
