// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Semantics.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialGlossaryDatabase : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "GlossaryImports",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    GlossaryId = table.Column<string>(type: "TEXT", nullable: false),
                    Sequence = table.Column<int>(type: "INTEGER", nullable: false),
                    PublishedAt = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    SourceAsset = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    SourceHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    Status = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    Error = table.Column<string>(type: "TEXT", nullable: true),
                    ReleaseId = table.Column<long>(type: "INTEGER", nullable: true),
                    ImportedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryImports", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "GlossaryTerms",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    GlossaryId = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryTerms", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "GlossaryTermRevisions",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    TermId = table.Column<Guid>(type: "TEXT", nullable: false),
                    StaticId = table.Column<Guid>(type: "TEXT", nullable: false),
                    Revision = table.Column<int>(type: "INTEGER", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    Term = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    Definition = table.Column<string>(type: "TEXT", nullable: false),
                    Example = table.Column<string>(type: "TEXT", nullable: false),
                    SchemaType = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    SchemaConstraintsJson = table.Column<string>(type: "TEXT", nullable: false),
                    KeywordsJson = table.Column<string>(type: "TEXT", nullable: false),
                    Scope = table.Column<string>(type: "TEXT", nullable: false),
                    ScopeUrl = table.Column<string>(type: "TEXT", nullable: false),
                    Citations = table.Column<string>(type: "TEXT", nullable: false),
                    TeamSource = table.Column<string>(type: "TEXT", nullable: false),
                    VerifiedDefinitionFlag = table.Column<bool>(type: "INTEGER", nullable: false),
                    PublishToDevHub = table.Column<bool>(type: "INTEGER", nullable: false),
                    ContentHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryTermRevisions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_GlossaryTermRevisions_GlossaryTerms_TermId",
                        column: x => x.TermId,
                        principalTable: "GlossaryTerms",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Glossaries",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    CurrentReleaseId = table.Column<long>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Glossaries", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "GlossaryReleases",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    GlossaryId = table.Column<string>(type: "TEXT", nullable: false),
                    Version = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    Sequence = table.Column<int>(type: "INTEGER", nullable: false),
                    PublishedAt = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    SourceAsset = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    SourceHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryReleases", x => x.Id);
                    table.ForeignKey(
                        name: "FK_GlossaryReleases_Glossaries_GlossaryId",
                        column: x => x.GlossaryId,
                        principalTable: "Glossaries",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "GlossaryDrafts",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    GlossaryId = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    BaseReleaseId = table.Column<long>(type: "INTEGER", nullable: false),
                    Status = table.Column<string>(type: "TEXT", maxLength: 30, nullable: false),
                    SnapshotJson = table.Column<string>(type: "TEXT", nullable: false),
                    PublishedReleaseId = table.Column<long>(type: "INTEGER", nullable: true),
                    CreatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryDrafts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_GlossaryDrafts_GlossaryReleases_BaseReleaseId",
                        column: x => x.BaseReleaseId,
                        principalTable: "GlossaryReleases",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_GlossaryDrafts_GlossaryReleases_PublishedReleaseId",
                        column: x => x.PublishedReleaseId,
                        principalTable: "GlossaryReleases",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "GlossaryReleaseTerms",
                columns: table => new
                {
                    ReleaseId = table.Column<long>(type: "INTEGER", nullable: false),
                    TermRevisionId = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryReleaseTerms", x => new { x.ReleaseId, x.TermRevisionId });
                    table.ForeignKey(
                        name: "FK_GlossaryReleaseTerms_GlossaryReleases_ReleaseId",
                        column: x => x.ReleaseId,
                        principalTable: "GlossaryReleases",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_GlossaryReleaseTerms_GlossaryTermRevisions_TermRevisionId",
                        column: x => x.TermRevisionId,
                        principalTable: "GlossaryTermRevisions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "GlossaryTermSubmissions",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    GlossaryId = table.Column<string>(type: "TEXT", nullable: false),
                    ImportId = table.Column<long>(type: "INTEGER", nullable: true),
                    DraftId = table.Column<Guid>(type: "TEXT", nullable: true),
                    Sequence = table.Column<int>(type: "INTEGER", nullable: false),
                    SourceType = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    SourceReference = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    Operation = table.Column<string>(type: "TEXT", maxLength: 20, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 500, nullable: false),
                    SubmittedStaticId = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    ResolvedStaticId = table.Column<Guid>(type: "TEXT", nullable: true),
                    SourcePayload = table.Column<string>(type: "TEXT", nullable: false),
                    BreakingChange = table.Column<bool>(type: "INTEGER", nullable: false),
                    IsValid = table.Column<bool>(type: "INTEGER", nullable: false),
                    InvalidReasonsJson = table.Column<string>(type: "TEXT", nullable: false),
                    TermRevisionId = table.Column<long>(type: "INTEGER", nullable: true),
                    SubmittedUtc = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlossaryTermSubmissions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_GlossaryTermSubmissions_GlossaryDrafts_DraftId",
                        column: x => x.DraftId,
                        principalTable: "GlossaryDrafts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_GlossaryTermSubmissions_GlossaryImports_ImportId",
                        column: x => x.ImportId,
                        principalTable: "GlossaryImports",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_GlossaryTermSubmissions_GlossaryTermRevisions_TermRevisionId",
                        column: x => x.TermRevisionId,
                        principalTable: "GlossaryTermRevisions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Glossaries_CurrentReleaseId",
                table: "Glossaries",
                column: "CurrentReleaseId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryDrafts_BaseReleaseId",
                table: "GlossaryDrafts",
                column: "BaseReleaseId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryDrafts_PublishedReleaseId",
                table: "GlossaryDrafts",
                column: "PublishedReleaseId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryImports_GlossaryId_SourceAsset_SourceHash",
                table: "GlossaryImports",
                columns: new[] { "GlossaryId", "SourceAsset", "SourceHash" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryReleases_GlossaryId_Sequence",
                table: "GlossaryReleases",
                columns: new[] { "GlossaryId", "Sequence" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryReleases_GlossaryId_Version",
                table: "GlossaryReleases",
                columns: new[] { "GlossaryId", "Version" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryReleaseTerms_TermRevisionId",
                table: "GlossaryReleaseTerms",
                column: "TermRevisionId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTermRevisions_StaticId",
                table: "GlossaryTermRevisions",
                column: "StaticId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTermRevisions_TermId_Revision",
                table: "GlossaryTermRevisions",
                columns: new[] { "TermId", "Revision" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTerms_GlossaryId_Name",
                table: "GlossaryTerms",
                columns: new[] { "GlossaryId", "Name" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTermSubmissions_DraftId",
                table: "GlossaryTermSubmissions",
                column: "DraftId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTermSubmissions_GlossaryId_Name",
                table: "GlossaryTermSubmissions",
                columns: new[] { "GlossaryId", "Name" });

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTermSubmissions_ImportId",
                table: "GlossaryTermSubmissions",
                column: "ImportId");

            migrationBuilder.CreateIndex(
                name: "IX_GlossaryTermSubmissions_TermRevisionId",
                table: "GlossaryTermSubmissions",
                column: "TermRevisionId");

            migrationBuilder.AddForeignKey(
                name: "FK_Glossaries_GlossaryReleases_CurrentReleaseId",
                table: "Glossaries",
                column: "CurrentReleaseId",
                principalTable: "GlossaryReleases",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Glossaries_GlossaryReleases_CurrentReleaseId",
                table: "Glossaries");

            migrationBuilder.DropTable(
                name: "GlossaryReleaseTerms");

            migrationBuilder.DropTable(
                name: "GlossaryTermSubmissions");

            migrationBuilder.DropTable(
                name: "GlossaryDrafts");

            migrationBuilder.DropTable(
                name: "GlossaryImports");

            migrationBuilder.DropTable(
                name: "GlossaryTermRevisions");

            migrationBuilder.DropTable(
                name: "GlossaryTerms");

            migrationBuilder.DropTable(
                name: "GlossaryReleases");

            migrationBuilder.DropTable(
                name: "Glossaries");
        }
    }
}
