// <auto-generated />
using System;
using Adr.Semantics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Semantics.Data.Migrations
{
    [DbContext(typeof(GlossaryDbContext))]
    partial class GlossaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryDraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlossaryId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseReleaseId");

                    b.HasIndex("PublishedReleaseId");

                    b.ToTable("GlossaryDrafts");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentReleaseId");

                    b.ToTable("Glossaries");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryImportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlossaryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAsset")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlossaryId", "SourceAsset", "SourceHash")
                        .IsUnique();

                    b.ToTable("GlossaryImports");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryReleaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlossaryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAsset")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlossaryId", "Sequence")
                        .IsUnique();

                    b.HasIndex("GlossaryId", "Version")
                        .IsUnique();

                    b.ToTable("GlossaryReleases");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryReleaseTermEntity", b =>
                {
                    b.Property<long>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TermRevisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId", "TermRevisionId");

                    b.HasIndex("TermRevisionId");

                    b.ToTable("GlossaryReleaseTerms");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlossaryId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlossaryId", "Name")
                        .IsUnique();

                    b.ToTable("GlossaryTerms");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermRevisionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PublishToDevHub")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaConstraintsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaticId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TermId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VerifiedDefinitionFlag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StaticId");

                    b.HasIndex("TermId", "Revision")
                        .IsUnique();

                    b.ToTable("GlossaryTermRevisions");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermSubmissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BreakingChange")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlossaryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ImportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvalidReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedStaticId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedStaticId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TermRevisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("ImportId");

                    b.HasIndex("TermRevisionId");

                    b.HasIndex("GlossaryId", "Name");

                    b.ToTable("GlossaryTermSubmissions");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryDraftEntity", b =>
                {
                    b.HasOne("Adr.Semantics.Data.GlossaryReleaseEntity", "BaseRelease")
                        .WithMany()
                        .HasForeignKey("BaseReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adr.Semantics.Data.GlossaryReleaseEntity", "PublishedRelease")
                        .WithMany()
                        .HasForeignKey("PublishedReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseRelease");

                    b.Navigation("PublishedRelease");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryEntity", b =>
                {
                    b.HasOne("Adr.Semantics.Data.GlossaryReleaseEntity", "CurrentRelease")
                        .WithMany()
                        .HasForeignKey("CurrentReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentRelease");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryReleaseEntity", b =>
                {
                    b.HasOne("Adr.Semantics.Data.GlossaryEntity", "Glossary")
                        .WithMany("Releases")
                        .HasForeignKey("GlossaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Glossary");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryReleaseTermEntity", b =>
                {
                    b.HasOne("Adr.Semantics.Data.GlossaryReleaseEntity", "Release")
                        .WithMany("Terms")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adr.Semantics.Data.GlossaryTermRevisionEntity", "TermRevision")
                        .WithMany("Releases")
                        .HasForeignKey("TermRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("TermRevision");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermRevisionEntity", b =>
                {
                    b.HasOne("Adr.Semantics.Data.GlossaryTermEntity", "TermIdentity")
                        .WithMany("Revisions")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermIdentity");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermSubmissionEntity", b =>
                {
                    b.HasOne("Adr.Semantics.Data.GlossaryDraftEntity", "Draft")
                        .WithMany("TermSubmissions")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Adr.Semantics.Data.GlossaryImportEntity", "Import")
                        .WithMany("TermSubmissions")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Adr.Semantics.Data.GlossaryTermRevisionEntity", "TermRevision")
                        .WithMany()
                        .HasForeignKey("TermRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Draft");

                    b.Navigation("Import");

                    b.Navigation("TermRevision");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryDraftEntity", b =>
                {
                    b.Navigation("TermSubmissions");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryEntity", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryImportEntity", b =>
                {
                    b.Navigation("TermSubmissions");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryReleaseEntity", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Adr.Semantics.Data.GlossaryTermRevisionEntity", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
